In [1]:
import numpy as np

In [5]:
x = np.array([1, 2, 3])

In [6]:
print(type(x))

<class 'numpy.ndarray'>


In [7]:
print(x.shape)

(3,)


In [8]:
print(x[0], x[1], x[2])

1 2 3


In [9]:
# change an element of the array
x[2] = 5

In [10]:
print(x)

[1 2 5]


In [11]:
# Now create a 2 dimentional array
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [12]:
print(y.shape)

(3, 3)


In [14]:
print(y[0,1], y[1,2], y[2,0])

2 6 7


In [15]:
z = np.zeros((2,2))

In [16]:
print(z)

[[0. 0.]
 [0. 0.]]


In [17]:
k = np.ones((2,4))

In [18]:
print(k)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
p = np.full((2,4), 6)

In [20]:
print(p)

[[6 6 6 6]
 [6 6 6 6]]


In [21]:
p[1, 1] = 10

In [22]:
print(p)

[[ 6  6  6  6]
 [ 6 10  6  6]]


In [23]:
e = np.random.random((2,2))
print(e)

[[0.79302253 0.27792111]
 [0.08518779 0.50467395]]


In [24]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1 2 3 4 ]
#  [ 5 6 7 8 ]
#  [ 9 10 11 12 ]]
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [25]:
row_r1 = a[1, :]
print(row_r1, row_r1.shape)

[5 6 7 8] (4,)


In [26]:
col_r1 = a[:, 1]
print(col_r1, col_r1.shape)

[ 2  6 10] (3,)


In [27]:
print(a[0,0], a[1,1], a[2,2])

1 6 11


In [28]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
Create a new array from which

## comment 1

In [ ]:
# Create a new array from which we will select elements and update them

In [31]:
r = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [32]:
print(r)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [33]:
d = np.array([0, 2, 0, 2])

In [35]:
print(r[np.arange(4), d])

[ 1  6  7 12]


In [36]:
r[np.arange(4), d] += 10

In [37]:
print(r)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 11 22]]


## comment 2

In [ ]:
# Boolean array indexing: Frequently this type of indexing is used to select the 
# elements of an array that satisfy some condition

In [38]:
bo = np.array([[1, 2], [3, 4], [5, 6]])

In [39]:
bool_idx = (bo > 2)

In [40]:
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [41]:
print(bo[bool_idx])

[3 4 5 6]


In [42]:
print(bo[bo > 2])

[3 4 5 6]


## find out datatypes

In [43]:
print(bo.dtype)

int64


In [45]:
bo = np.array([[1, 2.0], [3, 4.0], [5, 6]])
print(bo.dtype)

float64


## Array Maths

In [46]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[3, 4], [5, 6]])

In [47]:
print(x+y)

[[ 4  6]
 [ 8 10]]


In [48]:
print(x-y)

[[-2 -2]
 [-2 -2]]


In [50]:
# same result as print(x+y)
print(np.add(x,y))    

[[ 4  6]
 [ 8 10]]


In [51]:
print(sum(x))

[4 6]


In [52]:
print(np.sum(x))

10


In [53]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [54]:
print(x/y)

[[0.33333333 0.5       ]
 [0.6        0.66666667]]


In [55]:
print(x*y)

[[ 3  8]
 [15 24]]


In [56]:
print(np.multiply(x,y))
print(np.divide(x,y))
print(np.subtract(x,y))

[[ 3  8]
 [15 24]]
[[0.33333333 0.5       ]
 [0.6        0.66666667]]
[[-2 -2]
 [-2 -2]]


## We use the dot function to compute inner products of vectors

In [57]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

In [60]:
# Inner product of vectors (cross product of matrix)
print(v.dot(w))
print(np.dot(v, w))

219
219


In [62]:
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [63]:
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


## transposing a matrix

In [64]:
x = np.array([[1, 2], [3, 4]])
print(x)

[[1 2]
 [3 4]]


In [66]:
# transposing matrix --> makes rows as cols and cols as rows 
print(x.T)

[[1 3]
 [2 4]]


In [67]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])

In [68]:
print(v+x)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [72]:
v = np.array([1, 2])     # v has shape (2,)
w = np.array([4, 5])     # w has shape (2,)

In [71]:
print(v*w)

[ 4 10]


In [73]:
v = np.array([1, 2, 3])  # v has shape (3,)
w = np.array([4, 5])     # w has shape (2,)

In [74]:
print(np.reshape(v, (3,1))*w)

[[ 4  5]
 [ 8 10]
 [12 15]]
