## 1. Create a null vector of size 10 but the fifth value which is 1.

In [2]:
import numpy as np

In [8]:
x = np.zeros((10))

In [9]:
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
x[4] = 1

In [11]:
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 2. Create a vector with values ranging from 10 to 49. 

In [13]:
y = np.arange(10,50)

In [14]:
print(y)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 3. Create a 3x3x3 array with random values. 

In [15]:
z = np.random.random((3,3,3))

In [16]:
print(z)

[[[0.24686572 0.74238267 0.97067538]
  [0.52747258 0.20300312 0.16992039]
  [0.26477916 0.38074894 0.66133458]]

 [[0.86165642 0.22935089 0.21136039]
  [0.15826115 0.23694254 0.46511876]
  [0.65724191 0.10063205 0.08335289]]

 [[0.1755394  0.49290894 0.42879201]
  [0.4420479  0.89208898 0.10333422]
  [0.00718823 0.08041757 0.14813019]]]


## 4. Create a 10x10 array with random values and find the minimum and maximum values.

In [17]:
a = np.random.random((10,10))

In [18]:
print(a)

[[0.09415475 0.53383124 0.1499907  0.40893257 0.74671289 0.14191306
  0.83431312 0.23254333 0.24798628 0.86817886]
 [0.13490641 0.60067987 0.59251698 0.10406946 0.24325348 0.26281251
  0.48570408 0.91153344 0.25462804 0.59663612]
 [0.54445366 0.68498371 0.90409238 0.5139425  0.86285149 0.81111586
  0.23312677 0.47451994 0.79205345 0.4499008 ]
 [0.50085563 0.03823085 0.69550074 0.70755375 0.47530642 0.46647459
  0.52560995 0.61411281 0.04638161 0.46262102]
 [0.93064683 0.77821661 0.21286217 0.34029705 0.12469425 0.97491725
  0.76923256 0.67491917 0.92782482 0.64180361]
 [0.09503197 0.94768805 0.78948913 0.11289487 0.16246121 0.19414507
  0.69142322 0.93009468 0.4977088  0.12705113]
 [0.24252279 0.11065159 0.33289413 0.27654746 0.59935022 0.0213697
  0.47373895 0.68906897 0.69827053 0.59038575]
 [0.60336689 0.09215598 0.09552749 0.5071375  0.2672026  0.5137134
  0.14013374 0.5159346  0.52674932 0.27381796]
 [0.49295381 0.90409008 0.6337086  0.15088591 0.14391977 0.72626335
  0.78396667 0

In [21]:
print("Minimum values = ", a.min())
print("Maximum values = ", a.max())

Minimum values =  0.02136970136399219
Maximum values =  0.9916896226688225


## 5. Create a random vector of size 30 and find the mean value. 

In [23]:
b = np.random.random((30))

In [24]:
print(b)

[0.63053435 0.63040208 0.20373589 0.12408766 0.47677775 0.97295512
 0.48821361 0.78472001 0.78709735 0.65383931 0.34094245 0.66984409
 0.73145397 0.05744905 0.00263665 0.82122097 0.03472359 0.96696975
 0.31503718 0.15322819 0.39973507 0.16917574 0.84200867 0.82781814
 0.52602176 0.36035961 0.67615373 0.74322383 0.3439583  0.7684987 ]


In [25]:
print("Mean value = ", b.mean())

Mean value =  0.5167607524065272


## 6. Create a 2d array with 1 on the border and 0 inside. 

In [31]:
c = np.ones((10,10))

In [32]:
print(c)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [34]:
c[1:-1, 1:-1] = 0
print(c)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 7. Create a 8x8 matrix and fill it with a checkerboard pattern.

In [4]:
f = np.ones((8,8), dtype=int)
f[::2, ::2] = 0
f[1::2, 1::2] = 0
print(f)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 8. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.

In [3]:
m = np.diag([1, 2, 3, 4], k=-1)
print(m)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## 9. Create a random vector of size 10 and sort it. 

In [37]:
d = np.random.random((10))
print(d)

[0.19413589 0.96116748 0.99218259 0.87674516 0.22377934 0.53720754
 0.33243603 0.34985113 0.36521879 0.39819402]


In [40]:
print(" Sorted vector = ", np.sort(d))

 Sorted vector =  [0.19413589 0.22377934 0.33243603 0.34985113 0.36521879 0.39819402
 0.53720754 0.87674516 0.96116748 0.99218259]


## 10. Create random vector of size 10 and replace the maximum value by 0.

In [41]:
d = np.random.random((10))
print(d)

[0.3832341  0.44250927 0.19257305 0.9859812  0.60423801 0.5559439
 0.25239535 0.79649684 0.5002239  0.84356818]


In [57]:
max = d.max()
d[d==max] = 0
print(d)

[0.3832341  0.44250927 0.19257305 0.         0.60423801 0.5559439
 0.25239535 0.79649684 0.5002239  0.84356818]
